definitions:
  Message:
    properties:
      message:
        type: string
        x-go-name: Message
    type: object
    x-go-package: github.com/AlecSmith96/dnd-scheduler/entities
paths:
  /:
    get:
      operationId: request_1
      responses:
        "200":
          $ref: '#/responses/Message'
      summary: Get Homepage returns JSON welcome message.
      tags:
      - GetHomepage
responses:
  Message:
    description: Message field with the welcome message.
    schema:
      $ref: '#/definitions/Message'
swagger: "2.0"
